name: Main CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.x' # Adjust the version as needed

      - name: Build Projects
        run: dotnet build --configuration Release

      # Add additional steps as needed for testing, packaging, etc.
